### PR TITLE
Add `deriving show` for OCaml type definitions

### PR DESCRIPTION
**Pull request by kopecs**
Adds a derive for `show` so you can print debug the types defined here.

### CODE REVIEW

**Comment by kopecs** [comment]
Is it intentional that autogenerated files are tracked by `git`?

**Comment by kopecs** [comment]
Force pushing to add autogenerated files for now.

**Comment by mjambon** [comment]
> Adds a derive for show so you can print debug the types defined here.

You should be able to do this by passing a flag to the `atdgen` command in the `dune` file, rather than annotating each type definition in the atd file.

Right now, there's in-between option for setting this in the atd file but only in one spot at the beginning of the file. Maybe that would be a good thing to add to atdgen.

**Comment by mjambon** [comment]
> Is it intentional that autogenerated files are tracked in the git history? I would've figured these would've been ignored by git and we'd just generate them when the cli or core makefile ran a target requiring them.

The goal is to make these interfaces viewable by people who are not familiar with the code generators or don't want to deal with that. In general, this practice poses some problems (maintenance, security) but alternatives are more complicated to set up. To do things well, we'd need a source repo and a separate repo/tarball. The latter would contain the generated code, pushed automatically by a CI job.

**Review by mjambon — APPROVED** [review]

**Comment by kopecs** [comment]
> You should be able to do this by passing a flag to the atdgen command in the dune file, rather than annotating each type definition in the atd file.

"Should" as in this is currently possible and I should change the commands we use, or as a normative statement?

**Comment by aryx** [comment]
I would prefer to be able to set the default value in the file rather than in the dune file with special options to atdgen. It also generalizes better to other annotation-like features in other languages (e.g., python decorator, Java/Scala annotations).

**Comment by mjambon** [comment]
> > You should be able to do this by passing a flag to the atdgen command in the dune file, rather than annotating each type definition in the atd file.
> 
> "Should" as in this is currently possible and I should change the commands we use, or as a normative statement?

"Should" as in "it's currently possible but I haven't tried it myself".

**Pull request merged**
