### PR TITLE
Remove unique_id from semgrep_output_v0.atd

### PR DESCRIPTION
**Pull request by aryx**
This field was useful back in the day when the semgrep
engine was split between semgrep-core and semgrep-cli.
Now all the logic is in semgrep-core so there is no
need anymore for this unique_id field

test plan:
used in semgrep and everything seems to work fine

### CODE REVIEW

**Comment by aryx** [comment]
I will remove abstract_content is another diff.

**Comment by nmote** [comment]
It looks like this is included in the CLI output, is that correct? If so, have you checked to make sure that downstream consumers are not relying on it?

**Review by nmote — APPROVED** [review]
Looks like @brendongo approved https://github.com/returntocorp/semgrep/pull/5820, so that suggests to me that the App is not in fact relying on this info.

**Comment by aryx** [comment]
Yes I did before a 'git grep unique_id' in semgrep-app and there was no match (I should have put that in my test plan).

**Pull request merged**
