### PR TITLE
allow additional properties

### PR DESCRIPTION
**Pull request by brendongo**
- [ ] I ran `make setup && make` to update the generated code after editing a `.atd` file (TODO: have a CI check)

### CODE REVIEW

**Comment by brendongo** [comment]
Fixes https://github.com/returntocorp/semgrep/issues/8648

**Review by mjambon — APPROVED** [review]
looks good to me. Let's delay the merge until we have a chance to check the quality of error messages created by the OCaml implementation when an unknown field is encountered. See https://github.com/returntocorp/semgrep/issues/8648#issuecomment-1716665999

**Comment by aryx** [comment]
I think we can merge that; the OCaml implementation does not rely on the rule schema anyway, so we can independently improve things.
@brendongo can you add a big comment though before this important setting, like "# THIS IS IMPORTANT! we allow additional fields because X and Y. That does not mean you can write whatever rule you want, but for backward and forward compatibility reason, we don't want to crash if semgrep runs on rule using deprecated fields, or old semgrep runs on rules using new fields; We can just skip those rules in the engine without crashing at validation time" (or something like that).

**Comment by mjambon** [comment]
@aryx we can continue rejecting unknown fields in semgrep-core/osemgrep. We only need to be tolerant in pysemgrep because it doesn't check for `min-version`. If a new rule uses a newly-introduced field, it should set `min-version` appropriately.

**Pull request merged**
